server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booksys_db?serverTimezone=UTC
    username: root
    password: 123654
  mvc:
    view:
      prefix: /templates/
      suffix: .html

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



